server {
    listen 80;
    server_name twinplanet.cn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name twinplanet.cn;

    ssl_certificate /etc/ssl/certs/twinplanet.crt;
    ssl_certificate_key /etc/ssl/private/twinplanet.key;

    location /api {
        proxy_pass http://api:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 200 '双宝手帐 API Service';
    }
}
